# Generated by Django 5.1.7 on 2025-04-28 00:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_profile_is_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='code_created_at',
            new_name='token_expiry',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
