# Generated by Django 5.1.7 on 2025-04-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_email_verified_profile_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(max_length=6),
        ),
    ]
