# Generated by Django 5.1.7 on 2025-04-28 02:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_profile_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
