# Generated by Django 5.1.7 on 2025-04-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_profile_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
