# Generated by Django 5.1.7 on 2025-04-28 03:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_profile_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='token_expiry',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='code_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
