# Generated by Django 5.1.7 on 2025-04-28 03:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_profile_token_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
