# Generated by Django 5.1.7 on 2025-05-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_profile_token_expiry_profile_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='excels/'),
        ),
    ]
