# Generated by Django 5.1.7 on 2025-05-21 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_horario_remove_reserva_dia_remove_reserva_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
