# Generated by Django 5.1.7 on 2025-05-21 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_reserva_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.horario'),
        ),
    ]
