# Generated by Django 5.1.7 on 2025-05-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_usuario_reserva_user_alter_horario_dia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='dia',
        ),
        migrations.AddField(
            model_name='profile',
            name='excel_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(),
        ),
    ]
