# Generated by Django 5.1.7 on 2025-05-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_horario_dia_profile_excel_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='dia',
            field=models.CharField(default='Lunes', max_length=20),
        ),
        migrations.AddField(
            model_name='horario',
            name='max_reservas',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
