# Generated by Django 5.1.7 on 2025-05-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_horario_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('dia', 'hora_inicio', 'hora_fin')},
        ),
    ]
