# Generated by Django 5.1.7 on 2025-05-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_horario_dia_alter_horario_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='max_reservas',
            new_name='capacidad',
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(max_length=20),
        ),
    ]
