# Generated by Django 5.1.7 on 2025-06-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_solicituddias'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddias',
            name='dias_seleccionados',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
