# Generated by Django 5.1.7 on 2025-06-16 15:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_solicituddias_dias_seleccionados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicituddias',
            name='dias_seleccionados',
        ),
        migrations.AddField(
            model_name='solicituddias',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DiaSeleccionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='myapp.solicituddias')),
            ],
        ),
    ]
