# Generated by Django 5.1.7 on 2025-06-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_solicituddias_dias_seleccionados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicituddias',
            name='fecha_solicitud',
        ),
        migrations.AddField(
            model_name='reserva',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DiaSeleccionado',
        ),
    ]
