# Generated by Django 5.1.7 on 2025-06-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_solicituddias_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='aprobada',
            new_name='aprobado',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='capacidad',
        ),
    ]
