# Generated by Django 5.1.7 on 2025-06-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rename_aprobada_reserva_aprobado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='capacidad',
            field=models.IntegerField(default=5),
        ),
    ]
