# Generated by Django 5.1.7 on 2025-06-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_horario_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='dia',
            field=models.CharField(blank=True, default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
