# Generated by Django 5.1.7 on 2025-06-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_reserva_dia_alter_reserva_fecha_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tipo_reserva',
            field=models.CharField(choices=[('3', '3 días'), ('todos', 'Todos los días')], default='3', max_length=10),
        ),
        migrations.AlterField(
            model_name='solicituddias',
            name='opcion',
            field=models.CharField(choices=[('3', '3 días'), ('todos', 'Todos los días')], default='3', max_length=10),
        ),
    ]
