# Generated by Django 5.1.7 on 2025-06-29 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_profile_tipo_reserva_alter_solicituddias_opcion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('dia', 'hora_inicio', 'hora_fin')},
        ),
    ]
