# Generated by Django 5.1.7 on 2025-06-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_horario_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sheet_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
