# Generated by Django 5.1.7 on 2025-06-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_profile_sheet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
