# Generated by Django 5.1.7 on 2025-06-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_profile_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
