# Generated by Django 5.1.7 on 2025-07-06 04:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_asistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='user',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(),
        ),
    ]
