# Generated by Django 5.1.7 on 2025-07-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_remove_asistencia_user_asistencia_fecha_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='ocupados_manual',
            field=models.IntegerField(default=0),
        ),
    ]
