# Generated by Django 5.1.7 on 2025-07-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_membresia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membresia',
            name='invitados',
        ),
        migrations.AddField(
            model_name='membresia',
            name='nombre_invitados',
            field=models.CharField(blank=True, help_text='Nombre de invitados si los hay', max_length=200),
        ),
    ]
