# Generated by Django 5.1.7 on 2025-07-08 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_remove_membresia_invitados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membresia',
            name='nombre_invitados',
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('pagado', models.BooleanField(default=False)),
                ('plan', models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral')], max_length=20, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitados', to='myapp.membresia')),
            ],
        ),
    ]
