# Generated by Django 5.1.7 on 2025-07-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_remove_membresia_nombre_invitados_invitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitado',
            name='membresia',
        ),
        migrations.RemoveField(
            model_name='invitado',
            name='plan',
        ),
        migrations.AlterField(
            model_name='invitado',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invitado',
            name='fecha_expiracion',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='invitado',
            name='fecha_inicio',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='invitado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='plan',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral')], max_length=20),
        ),
    ]
