# Generated by Django 5.1.7 on 2025-07-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_remove_invitado_membresia_remove_invitado_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='plan',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral')], default='Básico', max_length=20),
            preserve_default=False,
        ),
    ]
