# Generated by Django 5.1.7 on 2025-07-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_invitado_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitado',
            name='plan',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral')], default='mensual', max_length=20),
        ),
    ]
