# Generated by Django 5.1.7 on 2025-07-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_invitado_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitado',
            name='plan',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral')], default='mensual', max_length=20),
        ),
    ]
