# Generated by Django 5.1.7 on 2025-07-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_alter_invitado_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='no_pagado',
            field=models.BooleanField(default=True, editable=False, verbose_name='No Pagado'),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
    ]
